import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import QueryWrapper from "@/components/query-wrapper";
import Nav from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Linkspot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative ">
        <ClerkProvider>
          <QueryWrapper>
            <ThemeProvider enableSystem attribute="class" defaultTheme="dark">
              <Nav />
              {children}
              <Toaster />
            </ThemeProvider>
          </QueryWrapper>
        </ClerkProvider>
      </body>
    </html>
  );
}
